/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aptests;

import java.net.MalformedURLException;

public class App {

    public static void main(String[] args) throws MalformedURLException{
         // Initialize your test class        
        TestCases tests = new TestCases();

        //TODO: call your test case functions one after other here
        tests.testCase01();
        tests.testCase02();
        tests.testcase03();

        //END Tests
        tests.endTest(); // End your test by clearning connections and closing browser
    }
    
   
}
